name: CI

on: [push, repository_dispatch]
env:
  INPUT_MVNCOMMAND: '-version'
jobs:
  centos7:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v1
    - name: Maven command
      run: mvn $INPUT_MVNCOMMAND
    #- uses: actions/setup-python@v1
    #  with:
    #    python-version: '3.x'
    - name: Python version
      run: python3 --version  
  macos:
    runs-on: macos
    steps:
    - uses: actions/checkout@v1
    - name: Maven command
      run: mvn $INPUT_MVNCOMMAND
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: mvn %INPUT_MVNCOMMAND%
