name: CI Build

on: [push]

jobs:
  item-1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        repository: hbfernandes/apache-vfs-browser
        ref: master
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn -B clean package -f apache-vfs-browser/pom.xml

  item-2:
    runs-on: ubuntu-latest
    needs: [item-1]
    steps:
    - uses: actions/checkout@v1
      with:
        repository: hbfernandes/pentaho-jenkins-shared-library
        ref: master
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven Build
      working-directory: pentaho-jenkins-shared-library
      run: mvn -B clean verify
      
